main: io.github.RealizmHF.Main
name: FactionFactories
version: 1.0
author: RealizmHF
depend: [Factions, SmartInvs]
softdepend: [HolographicDisplays]
commands:
   factory:
      description: Create a factory
      usage: /factory